<?php
/* @var $this NewsletterReports */
/* @var $wpdb wpdb */

global $wpdb;

require_once NEWSLETTER_INCLUDES_DIR . '/controls.php';
$controls = new NewsletterControls();

/* @var $this NewsletterReports */
wp_enqueue_script('tnp-chart');

$statistics_module = NewsletterStatistics::instance();

// Type selection from the type list directly on this page
if (!empty($controls->data['type'])) {
    // Nothing
} elseif (isset($_GET['type'])) {
    // Direct link to this page with a type specified
    $controls->data['type'] = $_GET['type'];
} else {
    $controls->data['type'] = 'message';
}

$email_type = $controls->data['type'];
$send_mode = $this->get_email_send_mode($email_type);


if (!isset($controls->data['days'])) {
    $controls->data['days'] = 180;
}

$days = (int) $controls->data['days'];

// Emails generated by Autoresponder should be managed in a particular way
$autoresponder = strpos($email_type, 'autoresponder') !== false;
$is_continuous = $send_mode === 'continuous' || $autoresponder;

if (!$is_continuous) {
    if (empty($days)) {
        $emails = $wpdb->get_results($wpdb->prepare("select send_on, id, subject, total, sent, type, status, stats_time, open_count, click_count, error_count, unsub_count from " . NEWSLETTER_EMAILS_TABLE . " where status='sent' and type=%s order by send_on desc", $email_type));
    } else {
        $emails = $wpdb->get_results($wpdb->prepare("select send_on, id, subject, total, sent, type, status, stats_time, open_count, click_count, error_count, unsub_count from " . NEWSLETTER_EMAILS_TABLE . " where status='sent' and type=%s and send_on>unix_timestamp()-$days*24*3600 order by send_on desc", $email_type));
    }
} else {
    // TODO: Get the emails IDs from the autoresponder!
    // TODO: Delegate Autoresponder to extract the email list? Should be a good idea!
    $emails = $wpdb->get_results($wpdb->prepare("select send_on, id, subject, total, sent, type, status, stats_time, open_count, click_count, error_count, unsub_count from " . NEWSLETTER_EMAILS_TABLE . " where status='sent' and type=%s", $email_type));
}


$report = new TNP_Report();

// Used to graph the trend
$overview_labels = array(); // X-axis labels
$overview_titles = array(); // Tooltip (with subject)
$overview_open_rate = array();
$overview_click_rate = array();
$overview_reactivity = array();

$total_sent = 0;
$open_count_total = 0;
$click_count_total = 0;
$idx = 0;


// Calculates the aggregates
$email_ids = [];
foreach ($emails as $email) {
    // Get updated statistics for each newsletter (cound be very slow if many newsletters need to be updated)
    $data = $this->get_statistics($email);

    $email_ids[] = $email->id;

    if (empty($data->total)) {
        //continue;
    }

    // Used later for the tabled view
    $email->report = $data;

    $idx++;

    $report->total += $data->total;
    $report->open_count += $data->open_count;
    $report->click_count += $data->click_count;
    $report->error_count += $data->error_count;
    $report->unsub_count += $data->unsub_count;


    if ($send_mode == 'standard') {
        $overview_labels[] = strftime('%a, %e %b %y', $email->send_on);
    } else {
        $overview_labels[] = $idx;
    }

    $overview_open_rate[] = $data->open_rate;
    $overview_click_rate[] = $data->click_rate;
    $overview_reactivity[] = $data->reactivity;
    $overview_titles[] = $email->subject;
}

// Updates the report populated with global data to have the percentages and other derived data
$report->update($this->get_benchmark());

if (!$is_continuous) {
    $overview_labels = array_reverse($overview_labels);
    $overview_open_rate = array_reverse($overview_open_rate);
    $overview_click_rate = array_reverse($overview_click_rate);
    $overview_reactivity = array_reverse($overview_reactivity);
} else {
    //echo "select count(distinct user_id) from " . NEWSLETTER_SENT_TABLE . " where email_id in (" . implode(',', $email_ids) . ")";
    $total_user_count = $wpdb->get_var("select count(distinct user_id) from " . NEWSLETTER_SENT_TABLE . " where email_id in (" . implode(',', $email_ids) . ")");
}

$type_options = $this->get_email_types();
?>

<link rel="stylesheet" href="<?php echo plugins_url('newsletter-reports') ?>/admin/style.css" type="text/css">

<script>
    // Used in graphs tooltips
    var titles = <?php echo json_encode(array_reverse($overview_titles)) ?>;</script>

<div class="wrap" id="tnp-wrap">
    <?php include NEWSLETTER_DIR . '/tnp-header.php' ?>
    <div id="tnp-heading">


        <h2>Overall Statistics</h2>
        <?php $controls->page_help('https://www.thenewsletterplugin.com/documentation/reports-extension') ?>

    </div>

    <div id="tnp-body" class="tnp-statistics">

        <div class="row">
            <div class="col-md-12">
                <form method="post" action="">

                    <?php $controls->init(); ?>


                    <?php if (!$is_continuous) $controls->select('days', ['180' => 'Last 6 months', '365' => 'Last year', '730' => 'Last two year', '0' => 'Since the beginning']) ?>
                    <?php $controls->select('type', $type_options) ?>
                    <?php $controls->button('update', __('Update Charts', 'newsletter')) ?>
                </form>
            </div>
        </div>

        <?php if (empty($emails)) { ?>
            <div class="row">
                <div class="col-md-12">
                    <p>No newsletters sent on specified interval.</p>
                </div>
            </div>


        <?php } else { ?>

            <div class="tnp-cards-container">

                <div class="tnp-card">
                    <div class="tnp-card-title">
                        <?php echo $is_continuous ? 'Sent messages' : 'Reach' ?>
                    </div>
                    <div class="tnp-card-value">
                        <span class="tnp-counter-animationx"><?php echo $report->total ?></span>
                        <div class="tnp-card-description">Total messages sent</div>
                    </div>
                    <div class="tnp-card-icon"><div class="tnp-card-icon-business-contact"></div></div>
                </div>

                <div class="tnp-card">
                    <div class="tnp-card-title">Overall Opens</div>
                    <div class="tnp-card-value">
                        <span class="tnp-counter-animationx percentage"><?php echo $report->open_rate; ?></span>%
                        <div class="tnp-card-description">
                            <span class="value"><?php echo $report->open_count ?></span> Total opened messages
                        </div>
                    </div>
                    <div class="tnp-card-icon"><div class="tnp-card-icon-preview"></div></div>
                </div>

                <div class="tnp-card">
                    <div class="tnp-card-title">Overall Clicks</div>
                    <div class="tnp-card-value">
                        <span class="tnp-counter-animationx percentage"><?php echo $report->click_rate; ?></span>%
                        <div class="tnp-card-description">
                            <span class="value"><?php echo $report->click_count ?></span> Total clicks
                        </div>
                    </div>
                    <div class="tnp-card-icon"><div class="tnp-card-icon-mouse"></div></div>
                </div>

                <div class="tnp-card">
                    <div class="tnp-card-title">Overall Reactivity</div>
                    <div class="tnp-card-value">
                        <span class="tnp-counter-animationx percentage"><?php echo $report->reactivity ?></span>%
                        <div class="tnp-card-description">
                            <span class="value"><?php echo $report->click_count ?></span> clicks out of
                            <span class="value"><?php echo $report->open_count ?></span> opens
                        </div>
                    </div>
                    <div class="tnp-card-icon"><div class="tnp-card-icon-rabbit"></div></div>
                </div>

            </div>

            <!-- Second row -->
            <div class="tnp-cards-container">
                <?php if (!$is_continuous) { ?>
                    <div class="tnp-card">
                        <div class="tnp-card-title">Opens/Sent</div>
                        <div class="tnp-card-chart">
                            <canvas id="tnp-opens-sent-chart" class="mini-chart"></canvas>
                        </div>
                    </div>
                <?php } else { ?>

                    <div class="tnp-card">
                        <div class="tnp-card-title">Subscribers</div>
                        <div class="tnp-card-value">
                            <span class="tnp-counter-animationx"><?php echo $total_user_count ?></span>
                            <?php
                            /*
                              $url = wp_nonce_url(admin_url('admin-ajax.php'), 'newsletter-reports-user-count');
                              $url = add_query_arg('action', 'newsletter_reports_user_count', $url);
                              $url = add_query_arg('email_ids', implode(',', $email_ids), $url);

                              <br>
                              <button class="button-primary" onclick="jQuery('#tnp-subscriber-count').load('<?php echo $url ?>'); return false;">Compute</button>
                             */
                            ?>
                        </div>
                        <div class="tnp-card-icon"><div class="tnp-card-icon-business-contact"></div></div>
                    </div>
                <?php } ?>

                <div class="tnp-card">
                    <div class="tnp-card-title">Clicks/Opens</div>
                    <div class="tnp-card-chart">
                        <canvas id="tnp-clicks-opens-chart" class="mini-chart"></canvas>
                    </div>
                </div>

                <div class="tnp-card">
                    <div class="tnp-card-title">Unsubscriptions</div>
                    <div class="tnp-card-value">
                        <span class="tnp-counter-animationx"><?php echo $report->unsub_count ?></span>
                        <div class="tnp-card-description">
                            Cancellations started from overall newsletters (cannot always be tracked)
                        </div>
                    </div>
                    <div class="tnp-card-icon"><div class="tnp-card-icon-filter-remove"></div></div>
                </div>

                <div class="tnp-card">
                    <div class="tnp-card-title">Errors</div>
                    <div class="tnp-card-value">
                        <span class="tnp-counter-animationx"><?php echo $report->error_count ?></span>
                        <div class="tnp-card-description">
                            Errors encountered while delivery, usually due to a faulty mailing service.
                        </div>
                    </div>
                    <div class="tnp-card-icon"><div class="tnp-card-icon-remove"></div></div>
                </div>

            </div>


            <?php
            if (!$is_continuous) {
                include __DIR__ . '/index-charts.php';
            }
            include __DIR__ . '/index-newsletters.php';
            ?>

        <?php } ?>

        <?php include NEWSLETTER_DIR . '/tnp-footer.php'; ?>

    </div>
</div>


<script type="text/javascript">
    jQuery(function ($) {

        var opensSentChartData = {
            labels: ["Sent", "Opens"],
            datasets: [
                {
                    data: [<?php echo $report->total - $report->open_count; ?>, <?php echo $report->open_count ?>],
                    backgroundColor: ["#49a0e9", "#27AE60"]
                }
            ]
        };
        var opensSentChartConfig = {
            type: "doughnut",
            data: opensSentChartData,
            options: {
                responsive: true,
                legend: {display: false},
                elements: {
                    arc: {borderWidth: 0}
                }
            }
        };

        if (!!document.getElementById("tnp-opens-sent-chart")) {
            new Chart('tnp-opens-sent-chart', opensSentChartConfig);
        }

        var clicksOpensChartData = {
            labels: ["Opens", "Clicks"],
            datasets: [
                {
                    data: [<?php echo $report->open_count - $report->click_count; ?>, <?php echo $report->click_count ?>],
                    backgroundColor: ["#49a0e9", "#27AE60"]
                }
            ]
        };
        var clicksOpensChartConfig = {
            type: "doughnut",
            data: clicksOpensChartData,
            options: {
                responsive: true,
                legend: {display: false},
                elements: {
                    arc: {borderWidth: 0}
                }
            }
        };
        new Chart('tnp-clicks-opens-chart', clicksOpensChartConfig);
    });
</script>
